### ISSUE TITLE
<img> | base 64 image not displayed

### ISSUE THREAD

**Issue by DhruvTatran** [SufficientlySecure/html-textview#102]
**Text is displayed perfectly, but the image is not rendered. A teal colour square box is displayed instead.
See code below for reference.**

htmlTextView.setHtml("A complaint \"Network not working\" logged into customer care. You called to customer to understand the exact problem he/ she was facing, what will be the first thing, which you will ask the customer to do so?<img width=\"95%\" alt=\"\" style=\"max-height: 150px; max-width : 250px;\" src=\"data:image/jpg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD//gA+Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2NjIpLCBkZWZhdWx0IHF1YWxpdHkK/9sAQwAIBgYHBgUIBwcHCQkICgwUDQwLCwwZEhMPFB0aHx4dGhwcICQuJyAiLCMcHCg3KSwwMTQ0NB8nOT04MjwuMzQy/9sAQwEJCQkMCwwYDQ0YMiEcITIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy/8AAEQgAsQE/AwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8AgEXtTtnbFWxFThDWRvcqCKniL2q2IqcIqAuVRF7Uoiq4I6cIqAuUxF7U8Re1WxHThFQFyn5PtSiE+g/KrohqRYM9qBXKIgwOlOEXtU01xZ2v/Hxcwxf78gFUpPEOiw8G8V/+uas38hTsFyyIj6U7yfasmXxhpUYO1LlvcIB/M0yPxclw2210u5lbtkgf40WC5siH2pwh7npXPT6pq0uS89rYJ6KN7/1/lWTc3Noebm8urtvR5Nq/lRYLnXy3djb/AOtu7dCOoMgz+VVX1/SUOBcGQ+iRsf6Vxjalbpxb6epPY7Cf1JpovtTlOIrQL9QB/IGnYVzrz4msV+5b3T/SMD+Zpp8UQ4+Wwuvx2/41y8VvrspB2qoPtVyPTdWP37mFR7kf40WQXNz/AISeEHJ0+4/Nf8acPFFt/FZXQ+gU/wBayk0y4/j1C3UfTNS/YFUfNqcJPtAT/WiwXNZPEmmt99biP/ej/wAM1Zi1jSpvu3san0fK/wA65a4VYfuXFvL9SU/xqg+p2sefPjH1Vlb+XNKwXPRY/JmGYpY5B6owP8qeYD6V5xFf6XO48q4VH9yVNaQur9Yx5OoXITtiTdQB2hgPpTfIPoa4v+0dXj5N9Mw+vP8AKm/25qaHP9oTqf8AaVT/AEosFztvJPpSeT7Vxg8RaqhyNQ3f70af4U9fF2qIRl7eT/ej/wACKLAdf5XtSGL2rm4fGsw/19lC49Y2K/zzWraeKtMuSFlL27H++OPzFA7l7yvajyvarcYSVBJGyuh6MpyDTjFQIo+V7UGL2q75dIYvagCj5XtTfK9qvmKkMVAFAxe1NMXtV8x+1MMXtQFysI6cI6nCU4JQMhEdOEdTiOniOgRXEdPEVNvr600y3867mEa9h3Y+gHeuM1LxjeXJZLFRbQ/3zy5/oKB3Ovurq0sE33dxHEOwZuT9B3rCuvGVjEStrbyzsP4j8i/rz+lcRLO005ZmknnPUkliaQRTMTkgeyc/r0osK5v3Xi7VJeI2htlP9xdx/M1kz6tdXORcXtxID/CXOPy6U2LT9xBckmtCGwVcHaAPU0xGTGGJzHbk+54qdYbtx0VR6AV0UGk3UwH2eynmz3VcL/30cCtSDwpqkmC5tLYe5Mp/IYH60wOQhsZQ27Az6lc/zq6Euyuw3DhP7qHaP0rsofBkfBuNQuJPaJVjH8if1q/D4U0iI5Nn5rdczO0n6E4oA84+zWob95Ipb0LZNXINNaQfubK4k9CsDY/PGK9Og0+2tlAgt4oh6IgX+VT+XQK6POodB1NsbNNZPd2Qf1zV5PDOsNjdJaxj/fZj+i/1ruBH7Uvl0Bc40eD7px+91PHtHB/UsasReDIFOZb67k9soo/Ra6vYads9qAucq/gmxkB23N2n1kyKpTfD8HJiu42PpKh/+vXcBKUJRYVzza48D6hGMpDDKB/cYf1xWNd+Gp4f9fZSIPUocfnXseyl2UDueDyaJGc4G0e1Vxpl1bNm3nZSPQ4r3W40mwu/9faRMT1O3B/Mc1kXXguxl5gkkhb0OGX/AB/WlZD5jyZNS1S2P76JZl9cc/pVyHWrSYYnRoW77hkV1174Jv4QTEqTr6oefyNc1eaK8MhjngZG9GXaf1pWsO6GNaWl4u6Mow9VNZ8+juuTDKw9jSvprRNuidkb2pwvr624mjEyeo60AZskd1AfnDcdxRDelThulbUN/Z3Z2Ftj/wB1+KbcaNDOCy/K3tSs+g7rqSaZq11p7iSzmwpOTGeVb6ivRdD1i31qE7R5c6D54ienuPUV5N9muLGZY2yyt0IrW027uNPvYLuHcHQ/MP7w7imSermKk8r2pbPUbG/VTbXEbsQDsDcj2xVox+1OwikYvakMftV3y6Qx0WAomKmmL2q8Y/ammOiwGeI6eI6mCVIE9qCiBY6xtf8AEFvokXloBLeOPkjz092q34k1lNC0xpQA1w/yxKfX1ry0ySzvJdXLl5XOWZjQA68vLi9na6vZTJKfXoB6Adqqpm4fAzt9u/41LFGbpskHZ296tsY4FBOFAoEENrhAm0Bc/dHQ/wCNWCIbfiRuf7q8k1Qa4mnbaj+VH3IHzGpbSGOKdJHYvg8qTjP40AdLo+i3mrHMUfkQ93YV22neHbLTsOE8ybvJJyc+3pVDTPFelRmOyliNmQAFJYMn/fQrqFw6BlIZSMgg5BpiIdmaXyxUwWnBKBEHlinbKm2UuygCHZRsqfZQE9qAIdlLsqbZ7UoSgCAJTtlTeXSiOgCAR04JU3l+1OCe1AEHl0uyrHl0uygCuEFGyrGyl2UAVvLqOa1iuIzHNGkiHqrrkfkaubKNlAHLX3gzTrrLQ7rd/wDZ+ZfyNcrqPgrULXLRxCdPWLk/989f516lspNmKLDueDXelI24TQ4I7kdK5+2vZ47yWO1lk+zoduWOQT7V7F8T57ex8MSS+VH9pkYJG+PmBry6KzNvptisgHnyoZZMD1PH6YpD1tcmtyxB3ck9SRzVtF46URQbQACD9KsiIheRQBX+44cEgg9V4Ir0Twfqk2p2UkNwS7w4xIepHvXnkg9q19K1u50Ixvbqjh/9ZG38Q+vagR6eY/ak2VV0bXLLWod0DbZl+/C33l/xHvWn5dMRVMdN8sVb2U0x+1AGYEqRVAH0p4WodQf7PplzMOqRMc/hQM8m8Uak2seIZQGzBCfLjH06n88/lWPNmacW6D5V++fX2pbUjc8zc4Xcf51NpERctM55Y5pIp7l4RpbwDOAAK52S7FzduwbKhsD2rqobA6vqdvpoYqJmwxHYAZNcOLZ9P1K4tJAQYpWQ59jTEb0PIB7GrKrVWzUyLgAk9gBW9aaNdyru2Ki+rnAoAzSg6g8iu+8DayXxp0z5B/1eT0PpXP8A9iSwnes9o5x90tuqtDb3enXizqPutuyh6UCPZAlO2VX0i/TVNNiuUPzEYcehq+FoEQhKUJU22jbQBFspdlS7aXbQBFtpdtSBaXbQBHtoC1LtpQKAI9tKFqTbS7aAIwtLsqTbSgUwI9tG2pcUbaBEW2gpUu2jFAEOyk21NtoK4oGeMfFG7/tPxHY6SjEpGQXA9T/9aoDYxvN5sozgYVB0UelReLrG70Tx39vvkY20zZSXHGCMfpU97qENrbi4ba6nG0D+P06VEd2W9lYtQukOAlvD+KZq012jrsks7Zl9k2n9K5iO7muJ2kcbADwgPArRs5ZZ7goD8gHOaoklurSGQFrbMZPVDzXOahJPFeBkG6JVAKjqK6r7LI8qpEd7k4CjOSa5q9E0OpTx3ERjcOVKn27UASWd66vHPbytHKpyrqcEGvT/AAv4pTV/9Euysd6o47CT6e/tXkM8Ztz58X3f4l/rWha3RbZNCxV1O5WB5BoA91KU3ZWT4W11dd00GTAuoQFlUd/9r8a3dtAjKC1T1mMvod8vrA/8jWkEptzD5tnNH/eQj9KGC3Pn1Afscw7mH/2WrmnSARKBTIY9s3lsP4duD9SP6VHZk20zQt1Q4/DsfypLYt7nW+EZEj8Y2RfHzh0GfUqa574laZ/ZvjR5UXCXYD49+9XIpntbuC9h/wBZDIHX3xXZeNvDx8b+HbXVdJIe5jXeqE8t6r9Qf5UxHIaZbJaWqFR+8YZLVofaAvzSt9D3rH0q8cf6BfI1vexfKY5RtJ/OoPEc72v2TGcM5B/KgDoWu4lGfm684qaMh1DK2QelcvbXBlTk8VuaM0s032ZAWY/dUdTQB1vhG6eDUzbDOycHI9CO9d6FrA8N+H5LIm7ul2ykYRP7vua6XbTJZFtpdtSbaNtAEe2l20/FKFoEM20bak20u2gCMCl21IEpwSgCILShalCU4JQBCFp22pQntTxHQBBso2VY2Ac1zGteNtN0mdrVFe5uQOVixhT6E0rgjf2UbK8ku/Eep3l001xeyR5PyxRMVC/QDrXXeE/E7TM9rqlyoUKDHJKdpPtz1ouOx1uym7asIY5l3ROrjsVOaGUIpZiAo6k8YpiKF5p9pqNs9teW0c8LDlJFyK+etatLa38cy6dZKyWEEu8RliwXAycZ969s13xnpVhZSi0uYru5yUCRuCFPqTXksVnFPez3jrmackuxfrk1LVy1oVrZSULnuc11vg/w1Pq0M9z56RReYEOVJJ4zxVCKwgMRG1h7qwOPwrs/Beq2NharpTkq7SFlkPRie3tTsI6DTtDstL5giBl7ytyx/wAK85+J9pDHqiyqgEkkKuxHchsZ/L+Ves3MkdrbvPO4SJBlmJ6CvEfEmpv4l16W4TItlIVPZR0/qaGCMEx7rUgjtWVpUjxStC4K4OMGut07Sn1nVbfTbcHDt85H8KjqazfEsESeNtQjth+6WUqAPYAUhm54T1FtN8RWz5/dTHypB6g//Xr2IrmvDrOB11C1QrhzIvH417rGpEa59KZLMwJTgnapAKeFoA8G1i2Nlrt1DjGyeRfwJ3D9GqlqEDOFuIRmVOCP7w9K674h2H2bxGZ1GFuUSTPuPlP6ba55EZ4uM/lSRbILG6WZAD+I9K6jwz4il0G6KnL2UjfvIx1U/wB5ff8AnXOReF9RuLa41XTP34jbE9so+ZRj7wHcVHa3ob5ZBtbpzTEe5mz0bxHZxzy21rfQkfK0kYbH58g1wvxG8DWMXhp7rTIXieA72TzGZSPYMTj8KxNI1m90ifzrGbaD95CMo/1FdFqvxQ02XTH0+4snF9MhXyycx/XPp7UMWp5bpjPKqEAkkYYD1HFdNp8F9b3MF3BG+9GDAioLCOOFVEaCNT7fMfwraiXcvIH1kcj9BQhs9Js/FelXEMYnuPs8xADLIhAB+uMVtxlJUDxuroeQynINeLyKBnBXHsx/rXTeCtVkttSS0eQmCY7dpOQD2PtTJseibaNoAySAB1JqyEqrqMMEunzwzzLGroRuLbcUCscn4g8dadpZ+z2UkV5d8hgr5WP64/lWDaeP9TE6vOkMkJPKqmD+BrzJtKvdN164iRDNCrlfNByGGeDmtuEsvBVsk4AqU7ltJHvNlcQ39nFdQMGikXII/lVkLXm/gfXHsLz7DdbhbTHALDGxv/r16eFqiGRBKXy6m2mnBPagCER4p4T2qUJShPWgRFs9qbI6QxmSVwiKMlielM1LUbXSbN7q7kWOJBnJNeQeIPEd54lu9oLRWSt+7iz192/wpN2KSN3xX4zkuS2n6PIVB4eYdce1cJIghbyo2LTH7zdcf/Xq0xEQMMPMp+83pU1taCLk8se5oQyO2tBEoLcue5q8lt8uXB9s5FPjj5yCuR2NTBmU8x/98kimBDGksDB7eaWM+qN/hUl9qOr32nS2EuozPDIMMN3zY+p5p++MnnI/3hn+WKcFDDAYH6N/Q0WA5gaO9pEkcPyIvYjr+NWIS8X3mce4Oa3TFs6/L9cr/iKY1ur8lAR64z+q0WsK5RE6uu0srfXrVeWUxfOG5XkN3FaH2KKQ4AOP9khv0ODVebTAQVDjB7Elf50ARa54p1DxCkdu5MNogA8sHlyB1Y1Qs7a4vJUsrOFpJHOAiD+dWn0mWPGdypn0/rXd+Gdc8O6PbrElpNBK335WAct+IpaBcs6ZpFr4F8OXWoXZV7wpmRx3PZF/GvHEWW7u5rtzmSRixPuTkmuz8eeJH8Q3q2NtvjsIecleZG9awILVAgVHx6ZFFhmt4O0ltR8Q245McB3ufpXsmzmsPwXoKaTpCzNtM9wAzEdh2FdHtpksxwKeBjr0pQKdt4P0oGeU+PfE2l3uqRaVHE7Xdvk+YQNoyOlc7AzkZLGqnik5+I1ztjCgJz+XWr8MbJCZGXCKMlj6VEdS2rWOp8E6g1pryQu+I7hTGfr1FdZ4g8BaXrpedEFreHrLGOGP+0vf69a8rtbySSZJID5ewhlYjnNdO/irXrnC/wBoMntGir+uM1RJjat4O1rQSZGi863HPmx/Mv491/EY964TXVmm1SxligdnQ4bauRivRp7i8uSftN/K+eoeZj+lRR2kf8IbH+xHRqMwbTzgoCwv/tMRya1IhKOCmPqRV9YI05Kj/gcgH6CrEcfGVVMf7EZb+dMVzMaOZ+F259ACakt7K8jlSSNpUcHKtgLg1p/vAPvSKB/edUH6U0LGx6xE/wDApDQFyWa/1efAudVlGeoNwf5LVcWXnMGeSSVj3WIn9TVpEcdBKB7Ksf8AOj5OPMaIj0llZv5UWEZk0flTNGQRjscZx+FMKYII4HqKuXQiYgoyk5xhIto/OoghxyKQxMnz1O8rjhm6/jXrWgavYX9pFbwXnnTRoAwZSpPvg15IFw2D0NWtPvZtK1GK6i6owyPUelAnqe2Yori2+ISBiF0qZh6iQYP6U1vH8jKfL0efPYlx/hTuKx2xIFc54j8VRaNMlrGqtcMu75s4UfhXlHjLx34n067jvEkuLW3JwqIBgn3yDXN6prGoa19mvJ53knkTcxY4P6VLkUone63PeeIblJZroMiD5IV+6D649ay5rWeCMRwx8t95/SsuKPUtLsI7jULpo5HG6O3ddzEevsKbb+LboXjW72BlKtghDn9KhVEy3BmvbWohXkfNVoJx71FFr2lSMUmD28o6o/GDWjGLadcx3Cc9A1WpJktNFTbThkdDVr7FJjKjcPVeaiKEdvzpiGbieoB+opMIeqkfQ07FJimAgDJ/q5ivt0pC8gOWiVvcDB/MUpFM5HQ4oESfaIzwwcezAOP15pwZWGEkH0D4/RuKhLvjBww9xSfujyyFfdTQA64JhjJxhj0IUr/LiqOD1J5qU4Y5XO3tmmt0oArzBTEdwHPSmWVq1xcRwKPmdgoqXGQWPI6Ct/wRapc+I42dcrGCw470Aeo2VotnYQW69I0C/pUhWpaQjNMkxgKcVyhA64pQKdnYpYjgDNIZ87eMPtOj+P5ru8tZPKfABK8EY6j1p07z6lpc7xRt5bLlQwwcZ966vxf44XWL+60OKyVUgGWlfkkjsB2rGtADaOPVTUR3NWU9N6ccitWMYcZAIz6ZrH0k/KBnpW0vXj9KoktlX52iTHsoSk+UffKf8DkLfypmwEZeTn86ULAP75/SmIesiL91/wDviMD+dSpKrfeLkY/ifP8AKoQyD7sa/ic08TOOmB9BQA8GTP7uFR77M/qacftJADTbR6FsfyqIyO33mJ+po20wH+VGT882foCf504LAo4Dsfc4pgWlApASF02kLCoPqeahj+ZefvA4NSAE9OaTynSTdtO1utACOm5fekA82P3HBqYLmmBGWTKjg9eaQDrAXcl3Ha28hUyHaoJAGfxrqE8M+ISOXI/7aD/GuXELtIGjJVgchh2Nei6F4nN28VrdxqshXHmBvvH6UAecePvDmoR6VG2oLcTRK2f3Z3Y+vpXJeGtRtbLU4ppjGvkH5EnXK49/evpplDqQwBB7EV5l8TPA/wDaFoL/AEu0j86PmRYowCw/DrUyWg4s4LxVqCTQG/jl+1TSEjejA7c+1YVrdxJFbzi6EXmEqiuwHI69CcfjVW2LWbS21wrJG+Ax28qR7UscaJ54hS2uS8e1WcHcp9VHGDWXKraGl3c6iW4lgsXE9oJZVIONgYAdenvTLaWxmtjclTayZxsR9vHr14rmheNaxRXUgun1TeRI9y+5CuMLgHnitBLi9e4XT7d49Zml2mJ2AVF4ywIIyfzFRylJnX6S001hJdWt/lVYBvNXlfxGP5GtO0ubuSNpJIoZUU9mDZ9x3rz5PEFk8UcE1tPGwyJhbH5Y+cfxcfrW9bakth52nafqdq00gBKO457gbhlfyNO7XUTSZ1KmCVsPFJEe4HH6Gka0Bcqkgz23jbVDS/EN/pmnzNqVpLOQv7t0+dB/wIAg1d0PxFpWrwzGeJbNkGWYPtyfQCrVRrcTgiOS2ljyGQ/Uciq7Ajr+tdFpo07VmJ0++DuOSjIQQPX5eKttoc9wCxiWYZ+8pVuPwwatVEQ4tHIfWo5BubYPqa6S70FUkwFaI46E/wBDzWbcaTNDkqysB36H9atSTJsZp/Sq8nJwPwqwwYA8c1BtYMWI46CmIjkOBgV6P4B0v7Npz3jr88p+U+1ef2NrJqGpRW6KSWbFe12lstpaRQIMKigUAyaiignFMkyRSyD9w/8AumlApX/1L/Q0hnzhfjb481QDuG/kK2tO5ix7VkaqAvxCvx/e3f8AoNaumNlMVEDWRnaaNkrKezEfrW6BwKxLf93qEyntIf51tqcgVRI/FOAFNBzxUiozHhc0xCinDJ6CpI7ed+ifpVmPTZpf4xn0zk/pRcZUC+pAp4wOp/IVs23hud8MY5seu3aPzNaVt4dtt37xoc+nmGQ/koqXNBZnLce9TRwTyHbHCzE+i5ru7fw/AmNsMrf7sKoPzY5rTi06OFQWihTvmWUt+gwKXOFjgIdF1KXA8rYD/eIWtOHwlcvgvKuT/cUn9elda95p1qP3mpQRn0iCj/E1QuPFGgW4w073LdlyWz+dJzBIyW8JpHEzG6UMozhjzj6DNUdLttJ1BXaG4ebYSpAUIcj65Na8ni6+kOzSPDd1KuOHaMqv8q4nTp9T0zxo76pZ/ZRebnaNTkL7mocn0LUV1OtePTrEbpEhjUd5pP8AHAqldGzCw3tm0bfvR80TZU/lxVLV7rRJbvzrlvNKjGzzSEP1ANQ2FvPq8C2ejWIFvG4+YcIv4nrTTYnY9cjbdEjeqg0tQJLFa28azzRoVUAktgdPeqc/iPRbf/W6lbA+iuGP6VsZEep+FtE1gH7bp0EjH+MLhvzHNcVqnwZ0q43Pp95Nat2VxvX/ABro7nx9o0JxEZ52/wBiPj9cVlT/ABCuZTtstLx6NM+f0H+NS4plJyOC1L4W+KdPU/ZjFfQjoquD/wCOtXI3trdafc+TqmkTRSkHG0Mh/AHivWZ9b8Tahndc/Z0PaJAv6nmsqWyRpPNvbnzJPV2LH9ankK5jzAXVrHDLaRX01uJsCRLhCitjsSMirBt5DY28VrbxBoyWNzat8zZ9WB7V6K0Gnyr5X2MXGezKCDVZfhe+qSiaxtJNObqHjYoPyNDgtwUzjNq6ZfLDpV+9lFcBQ007FmjI6nK+pqddd1R4dk1jFqLQ7nlmnAG5OgxgBv1re1bwL4o00bfsP26Jf+WrASE/lzXNXUC5MV1bT2rnGdvPP0bn9azcbGidzZsPEmgwSKlst/YTSqAzwfvI1Y/wnfgj866Lw5cyWd9JJp3iGw1CTnNtLIYnB78NwfwNefz280unrZ299G8G/wAwxv8AId3TPP8AjVe8jntHtvLsmtFRNkksGQZB3Oc4zU8o7nrNz4t8VaY0h1LRGuLUksp8vzFA/wB4ZrP1vx5b6ho0cGk2UlpeyPj5ABz9O9edWWv63pMsyeH7y7WKQgoJGJI/DOP0rsfDlrJc3R1PW7qE6i3LRjC498DgGnZ2ErXNiK4a30xH1GGOSQgbmZdrA/UUMLBlAzPFMU3KvDA1NNawyazaXlwGktIwzMq/MCQOBj39ay5EmmuprxkIubt8RwAY2DoBSjKVxuMbGp4Siub7XohHG0YibLuOwr14kVznhTQl0PTv3hDXUvzSN/St0vXStjnY9mFMLVGz1GZKYiNRSuP3T/SkPCnHpXifxL8R67a6n9ngu7mC3x/ASoNKTsVGPMV9T0QzeL7y/wDMYDeV27fbFT29isHAbA9SaxPD+ufbwkN1I3mqfm55cV30cdjb2huiq+UoySRmovYuzb1MKOwheQsiB3Jydq5p1ytvYBXu8xRnjL8VqW/iS0N3FAtvOolOEYIMH8jWV8RNMD6VHqCNIXhcZTPy4PfFS5spQQHXNHtdmxWnLdPLiZs1Oury3PFro1wQeQZCI65ey1DV7u1SO0swQOA+AP1rVhsdaljH2m+hhz0VSWP6UlGpLRIG6cdWzpLGWcnddLp9qvo5Mh/U4rROvaXZqDNq7NgYKQYjH6c1yK+HrXcGubm7uCewwi/nzWhFpenQKoXTYSeoeRi5/n/SuiGArz6GE8bQh1Nc+M9G3k21hJdSdMsGkP65qzH4r8S3eE07QZlXoGZAi/maq29/dQRiO1aJFxjEMQUj8cVFPfSsd09230nkx/KuiOVyXxySOaWZQekItl+V/FtwM3uqWOnqeqmbcR+C1VOn2snN74gv7w90toyqn8TVeDfcnNpDcSv1AigZx+Z4rTh8O65c4KacYcn7084X/wAdXNWsLhYfHO5P1nEz+CFivHb6HAMwaP57D+K6nLZ/Cr0esyxLiygtLbH8MUAB/Or0fgu/eIebd20UncxRk/qf8Krz/D67nP73U3kHoXIH5Cnz4WHwwuTyYufxTsUbrW7pwfPv3Q9CjyhR+QqOKBbmGVtyqZUK5L+vfmrifDeWM5jnhU+ozn+VSj4e3BPN4v5n/Conik4uMYpIuGFtJSlK7MBPB9kjq7XMZI/vSCtJtPhSHYdYKgDgG5JA/AVor8Oyfv3v5KTVmP4d2Y/1l07H2X/69cljsucrJp+k5zNqaOe+FLfzqIR6BB0e4mPoFxXdReBNIj+8JX/ED+laEHhfR4Pu2asf9ok0WFc87F7aZAtdKLt2MhJq3Db69eYFrYCJT3WPH6mvS4rO2gGIreJP91QKmp2Fc8+g8F6vdENeXaxj03ZP6VsWfgXToMNO8k7fXArqaKLBcqWumWNkuLe1iT3C8/nVuiimIKq3em2V+hS7tIZ1P/PRAatUUrDucZqXwx8PXwYxQvaue8TcfkawYvhD5N4rJq7/AGcHlQmCR6da9RoqeRFKbMK38H6FbW3lrp0G4jDSBQGP4iuX1T4RaLcyNLZXNzZO3JCtuGfx5r0FnqJm96fKhKTPKbT4aeINNv4xDrEUtkW+fOVbH0ruNO8K2On3ou2kknmUYUyEEL9K2Wk96iMnvSUUgcmywZKjaSoC9ML1QiYyUwyVCXphkoCxeBqhq2hadrlq1vfW6SqR1I5FXQ1PBo3BaHiPib4SX+mSNe6DI08ancIv41+nrTPDniVrUG01OF45F4aN0IyfbNe6BqTyoS+8xRl/720ZqOTsaKfc4GPUp71UFrpl5cYXCbYThR6ZPFcp4n8TX9lvsrzQZUifhvOHUexHFe4KcCmzW8FyhS4hjkU9Q6gj9aOQOc8I0/WNHltlEb+U2PuPkMv+NbECyXeFtLS5uge8dsxGf94jFer2+i6TbNug060jb1WFR/StBVCjAAA9hXdTxlWEeVWOKphKU5czueYW/hjXbnG3T/JT/p5nA/RcmtS38B3rPvuNRhg7lbaH+rH+ld5RUSxNaW8io4alHaJzEHgbTFObmW8um7+ZMVB/BcVrWnh/SLE5ttNtY2/vCMZ/M81o0Vg23ubLTYQKAMDp6UtFFABRRRQAUUUUAFFFFABRRSEgUALRTd4o3igB1FM8ykMtAElFQmWmGX3oAsbhTDJ6VXMvvTGl96QFtXyetK0oVTVHzsUx5ie9Aydpct7Ux3x3qsZPeo2l96AJWk5qMvULSe9RtL70hk7SVGZKgaX3qFpfegCyZcVGZarNL71E0vvQB0g61ItFFMQ4daetFFAEgpwoopgOXtTx0oopIQtFFFMAooooAKKKKACiiigAooooAKKKKAGtTDRRSAaaQ0UUAJTaKKBiGozRRQA01GaKKAGmmGiigERmo2oopDImqJqKKAIm6VE1FFAEZqFutFFAH//Z\" ></br>",new HtmlResImageGetter(htmlTextView));

**Comment by dschuermann** [comment]
base64 is not supported.
