### ISSUE TITLE
support span tag

### ISSUE THREAD

**Issue by shingohu** [SufficientlySecure/html-textview#111]
can support span tag?
like this
`
<span style="color:red;"><strong>（修改颜色）公文标题应当正确简要地概括公文的主要内容，一般由发文机关名称或规范化简称、发文事由、文种三部分组成。在特定情况下，还可使用“省略式”标题。如果撰写非重要公文时，可省略发文机关名称。故A项错误，应排除。而命令、公告、通告等公布性文种一般可省略“事由”，故B项也错误，应排除。而“主送机关”在公告、通告、公报等周知性文件中是不需要标注主送机关的。故D项也错误，应排除。所以，正确答案是C。</strong></span>`

**Comment by dschuermann** [comment]
You can use the font tag for this or open a pull request to implement support for span tag.

**Comment by dengyuhan** [comment]
maybe it can help you.
[dengyuhan/html-textview](https://github.com/dengyuhan/html-textview/blob/upgrade/NEW-README.md)
