### ISSUE TITLE
Clicable=false not work

### ISSUE THREAD

**Issue by zigzag-mobile** [SufficientlySecure/html-textview#113]
For example i have something like this
```
<LinearLayout android:id="@+id/wrapper" ...>

   <org.sufficientlysecure.htmltextview.HtmlTextView
                        android:id="@+id/v_total_sum"
                        android:text="text with tags" .... />

</LinearLayout>
```
If i set listener for the parent view like:

`getElementById("wrapper").setOnClickListener(...)`

and tap on **HtmlTextView**, it dont trigger listener.

How can i fix it?

**Comment by untungs** [comment]
@the-devil-you-know did you manage to get it working?

**Comment by alen252** [comment]
I have the same problem.
