### ISSUE TITLE
YouTube support

### ISSUE THREAD

**Issue by kimkha** [sufficientlysecure/html-textview#13]
Currently, YouTube and other online video become famous, TextView should support it.

My recommend:
- Display a thumbnail image with Play button overlapping.
- When click on thumbnail image, a video player will run (we don't need to implement video player, just use default)

**Comment by dschuermann** [comment]
YouTube support is definitely out of scope. HtmlTextView is only meant to display _simple_ HTML. But you are free to fork the project.
