### ISSUE TITLE
How to link to another local file and open links inside textView not in browser

### ISSUE THREAD

**Issue by vahidsis** [SufficientlySecure/html-textview#138]
Hi
I'm novice and
I tried to open a link inside textview. the link is refer to another local file in the raw folder and i like to open it in textview. 
could anybody give me any idea?
Thanks in advance

**Comment by dengyuhan** [comment]
I added a custom click event for the a tag, you can try.
[dengyuhan/html-textview](https://github.com/dengyuhan/html-textview/blob/upgrade/NEW-README.md)

**Comment by tho9x** [comment]
thank you @dengyuhan
