### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by dlvenable** [SufficientlySecure/html-textview#158]
Hello.

What existing support or plans are there to support extending how tags are rendered?

In our investigation we haven't been able to extend the basic functionality in HtmlTagHandler. We do think there could be some approaches which might permit this. One would be to use the factory method pattern for creating new span objects.

For example, when a bullet tag is detected, the HtmlTagHandler creates new objects of `BulletSpan` by calling `new BulletSpan(...)`. This type of behavior could be delegated to a factory class with a method like `createBulletSpan(...)`. Thus, developers would have an option to changing the actual span produced. You can see where the new `BulletSpan` is created in HtmlTagHandler line [214](https://github.com/SufficientlySecure/html-textview/blob/master/HtmlTextView/src/main/java/org/sufficientlysecure/htmltextview/HtmlTagHandler.java#L214) and line [223](https://github.com/SufficientlySecure/html-textview/blob/master/HtmlTextView/src/main/java/org/sufficientlysecure/htmltextview/HtmlTagHandler.java#L223).

If this is something you'd be interested in having, we could create a PR for it.

**Comment by dschuermann** [comment]
Not sure if this approach is needed. I mean this is a very small library, so if you like to change stuff, I would propose forking it ;)

**Comment by dlvenable** [comment]
Thank you for considering this. Yes, we were considering whether forking as an option, but also wanted to see if we could stay with the project to get bug fixes as well. But we'll fork it.
