### ISSUE TITLE
Package HtmlTextView 2.0.0 is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Package HtmlTextView 2.0.0 supports: net (.NETFramework,Version=v0.0)

### ISSUE THREAD

**Issue by Tanyak05** [SufficientlySecure/html-textview#165]
Package HtmlTextView 2.0.0 is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Package HtmlTextView 2.0.0 supports: net (.NETFramework,Version=v0.0)

I get this error when I am trying to install the package. 
I am using VS2017 and my project are targeted to Android 8.1

**Comment by dschuermann** [comment]
I am not the maintainer of the Mono package. This is the Android version. The last version is 3.7 btw.
