### ISSUE TITLE
On Android Api 29 when clicking on a http link the app is crashing

### ISSUE THREAD

**Issue by SavvasMes** [SufficientlySecure/html-textview#168]
I get the error:

`android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag.`
 When I click on a link on textview this only happens with API 29. On API 25 it is working fine and asks me if i want to open the link in Chrome

**Comment by dschuermann** [comment]
Cannot reproduce with 3.7's example app.

Please try 3.7. If it does not fix your issue post your code here that leads to the crash.
