### ISSUE TITLE
.SVG image format not supported?

### ISSUE THREAD

**Issue by imarindam** [SufficientlySecure/html-textview#169]
First of all Thank you for this Library.
However, I tried fetching a HTML text from website. In this text the img src containts image in .svg format. That image is not visible in this view. Although PNG is supported. 
Can you please tell me what should be done?

**Comment by imarindam** [comment]
Here is the rendered content for your reference:

`<p>Find the central angle corresponding to Income tax.<br /> a) <img src="https://asedusolution.com/wp-content/ql-cache/quicklatex.com-1deabeeb619b27d77065472492d82ef0_l3.svg" class="ql-img-inline-formula " alt="&#49;&#48;&#50;&#94;&#123;&#92;&#99;&#105;&#114;&#99;&#125;" title="Rendered by QuickLaTeX.com" height="15" width="33" style="vertical-align: -1px;"/><br /> b) <img src="https://asedusolution.com/wp-content/ql-cache/quicklatex.com-f385390a3899563a18470a5241f73f4d_l3.svg" class="ql-img-inline-formula " alt="&#49;&#50;&#48;&#94;&#123;&#92;&#99;&#105;&#114;&#99;&#125;" title="Rendered by QuickLaTeX.com" height="15" width="33" style="vertical-align: -1px;"/><br /> c) <img src="https://asedusolution.com/wp-content/ql-cache/quicklatex.com-c363e76eed6925c9eb04eb43e9893282_l3.svg" class="ql-img-inline-formula " alt="&#49;&#49;&#56;&#94;&#123;&#92;&#99;&#105;&#114;&#99;&#125;" title="Rendered by QuickLaTeX.com" height="15" width="33" style="vertical-align: -1px;"/><br /> d) <img src="https://asedusolution.com/wp-content/ql-cache/quicklatex.com-7e3e94fec5538eaeb5eb5570af28a371_l3.svg" class="ql-img-inline-formula " alt="&#49;&#48;&#55;&#94;&#123;&#92;&#99;&#105;&#114;&#99;&#125;" title="Rendered by QuickLaTeX.com" height="15" width="33" style="vertical-align: -1px;"/></p> `

The output should be like the following:
> <p>Find the central angle corresponding to Income tax.<br /> a) <img src="https://asedusolution.com/wp-content/ql-cache/quicklatex.com-1deabeeb619b27d77065472492d82ef0_l3.svg" class="ql-img-inline-formula " alt="&#49;&#48;&#50;&#94;&#123;&#92;&#99;&#105;&#114;&#99;&#125;" title="Rendered by QuickLaTeX.com" height="15" width="33" style="vertical-align: -1px;"/><br /> b) <img src="https://asedusolution.com/wp-content/ql-cache/quicklatex.com-f385390a3899563a18470a5241f73f4d_l3.svg" class="ql-img-inline-formula " alt="&#49;&#50;&#48;&#94;&#123;&#92;&#99;&#105;&#114;&#99;&#125;" title="Rendered by QuickLaTeX.com" height="15" width="33" style="vertical-align: -1px;"/><br /> c) <img src="https://asedusolution.com/wp-content/ql-cache/quicklatex.com-c363e76eed6925c9eb04eb43e9893282_l3.svg" class="ql-img-inline-formula " alt="&#49;&#49;&#56;&#94;&#123;&#92;&#99;&#105;&#114;&#99;&#125;" title="Rendered by QuickLaTeX.com" height="15" width="33" style="vertical-align: -1px;"/><br /> d) <img src="https://asedusolution.com/wp-content/ql-cache/quicklatex.com-7e3e94fec5538eaeb5eb5570af28a371_l3.svg" class="ql-img-inline-formula " alt="&#49;&#48;&#55;&#94;&#123;&#92;&#99;&#105;&#114;&#99;&#125;" title="Rendered by QuickLaTeX.com" height="15" width="33" style="vertical-align: -1px;"/></p> 

But it is showing blank in place of images.

Please help.
Thank you in advance.

**Comment by imarindam** [comment]
Please reply sir.

**Comment by dschuermann** [comment]
Yep, SVG is not supported. I suspect it never will be supported as it would require additional external libraries to parse SVGs.
