### ISSUE TITLE
Click event on link?

### ISSUE THREAD

**Issue by kimkha** [SufficientlySecure/html-textview#17]
Can I catch an event when clicking a link in HTML? Currently, it's open the web browser, I want to handle some link schema in HTML. Please help!

**Comment by dschuermann** [comment]
You could integrate something like this: http://stackoverflow.com/a/19989677

But it's out of scope for this small library.

**Comment by dengyuhan** [comment]
I added a custom click event for the a tag, you can try.
[dengyuhan/html-textview](https://github.com/dengyuhan/html-textview/blob/upgrade/NEW-README.md)
