### ISSUE TITLE
Not loading the picture href base64 encoded

### ISSUE THREAD

**Issue by AhmadIzaz** [SufficientlySecure/html-textview#176]
This is what my html looks alike ..

`<h1><b><u style="font-family: tahoma, arial, helvetica, sans-serif; color: #3399ff;">About Us</u></b></h1><div><a href="https://www.youtube.com/watch?v=vvhC64hQZMk"><img id="pzxUjPL8jT6NcM:" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASUAAACsCAMAAAAKcUrhAAABmFBMVEXJZ2depdnu7u3ftYz+/v5MS0uQkZHzuIRFRUVRUVHW1tbWrIXmrn4/Pz9JSEjGoH342MJvcHBfquDRaWlpaWn7wImNjo783MmVlpbHYGTguY7xz7xDQkJ2dnbIYmLg4ODMzMzGW1xKQjzx9vZkZGRkUFCioqK6urqurq52U1NLRkNQV15bW1thT09RZHOkhIQ1QkLMdXU3NzeDhIROntZRXWVRZ3jMd27KbmrQhnXcroHPp4JWTk3csrNBSUnEVFXTkXrZpIOwX1/Vz9G5dHT16Oe3lHRamMNXiq3boqLw2tmLu+Lf6/beqan2za7jyMnOnnPPg4SXXFyyWFnXk5OFWFkpQECjWFgqKirQrK7fqZrluKXeoJbrxqyii3Hsx67ZzMLVv72MeHqsfX6SZWaZi4u4dnfv4dVVepOynox9b2FwZVvWtJO4gW0cLjJZP0GlmY7Lr5S5kn+qjG3GsaUcIia5qJqtzurK3/Gexeacrbj/x5iIq8T/v30tkND81rtDdpa0cGJSk8JumbopUmzim3mBkJjYh3HjmupHAAASMklEQVR4nO2djVsaSbbGEWzoBrojCAimaWglyBAmUegZ0ShqdsTRxKizZjfOXpPMnbsbY5zMunGd2RiS2Y9s/u1bVV39SXfTgAldxPd5kqhRAr+c89apUx/4fFcaDo0DDfo5eF7j3y0x311h6qAvGwzTYO5ecbKX8HuOQWrcuOJkJ3F/tEhTmNPDQT8bj2ple3R01F9jESeuMXt30E/Ii1rZGUXKJViGooFmr5LOLMG3PqpohmYRpatgMkmY0yCN5vIViKnx3aCflcck7mmMRsPhcC5bBZi+uEo5vZBvY02HoXKlKk+XryjpJOxokPxhWbk8xf5h0E/MSxq/UfObIUEl/ngVS5oYhqoWsW/rIIX3hEE/M89o/C4qtTlmxgTpd74rSIrG/9iQZyQMm8jpIf3weTPKZIQMEsQw/lCBBNLuUVHFlDtYGfTzHIgymXp9fn5hYXV19fvv/wT0/f9kfONf6CDRdDWLMeU2xUE/30+uTMY3v7oWmJQVCFzHWsssqYwYDs5JWCaPOO19ZpAQoQhkEwkoOsSUJh83jJBomq+WAKb65+RJgNCCTAhKoxQInBweHj45DERoBRKt6lHqM/JtYEMLayohyEhPSVGNNUOiZx9+JtlmJtQeS1hPRvMVmpGbSQqkz2NlIJOZh0ZtETjtgvOSEkfrIX0W7e5MfTUwaZlcbVo8Cct9kkJVo+QbfkjArNdcRtFi4PBpeFpuJuVSGFPjxqBfwUcXzDSMyDmUJhEhAEdtJqFeEsi2oW+6yZmGZU8JYFz78AMsHHPTuj5JLs+wQ+/bKNM6ZxkgtFrPZP43DCj5TX2SXJYd6maSLtOcCE0GVudBlenzcSxb9Lc3k3L1IYZkyDR7RGsLdYRo/O4sx1F0JYwXAbRm0vDW2yDT2mpHqzxb8GXkHxj/bpZDC7dsza+HlPthaOvtTOdhX8szpPGHGBIot9mizpQOhhdSJ8OenIys1jVEcBGgQanNJF7tJYVz+zaQhLk5whMxs+oICVqRT48IaMnYJ2GZvOMigDD352DwNuHNb2dICyZCwLdpygBJ6SX9zrqZJPhuB5F+JBhTZs2J0ZrPxMgnfvNSg6TO2qqpnM3gJvwYVPUNsZwWnEKpLZB8KwejuQKr9rdV/eH/LC1J+EtQp/SfSa2lnNItEomszhuiSdxC+20YzgRp1rLeRoakMUoV6AaRW3Sc8i2CpVVJ2s6kIkvpITWsmknAkNLBtAYpRnMUR+Q8eN4+3yI6yRW3ftONX9dLapQtHlkAhpQtFGIpzKgGSnWKTEoZV4xkUKv1ff2mm1xQwTR7wyqQ/pKuJaBiacSoQlMUoZRs862NEdDiM+POpFyJ5eVFgPYXDgwpFStASIVKGhoST1HEUrLLNytIuzpIuJkEe0lWzSRYIcmMEgyfTSNDIpeSTb5ZMYpE/BokbQ9AtmqxCIAMSWbEFkCyUYBRmVhKdvlmxegaA/fbPBs7hN/wVJvdFn9vftXCNwAMAxlV+EpNNiRu6oghlFLGrp5sZxRoUgxVfT65CNcCnjwJBNRm0pzpQYU6MKRasMAUChSXTQcTMNmmbm3ESaVUdw/pcYNpHKO/fIK2BQRO8M4kU70tCLdhshViMIRi6XQWMWK+jY+MEEopY9f5v3NN1Z07CNIxgNSUmeLdE4uWzSQw+iuGlA6mgCGBZCuXISNSKdn3S3SUEKnIC4p6EcHffahRMjeTgCHJFVKiQjPpdAoaUnnqaARBIpSSfdEdMVK6xlCNY+2bMaV8OHyyqp/gCT61QqJo1ZC+2pAZkUrJoRNgiKQmRTHXdN+MginwPByG5biKCRpSUBn9oSHB6UiZ+VZhRCYlW1MyU3rcwLatLmBevw7GuJmn8qxFmQWj/gglj/7AkBiYbNyRxohISs6d7khThfQsfxxR1sIxphPwi3m6GNEw4f5IusJzPFOTDYmb+npED4lASraVElaziTk9G9PDUz+qvlpUqwRoSEprpBarpdMJ3mhIsgislxzaJTiYEKc7J4YvYkyTzUc/6WuqH/V9tnSWMhsSqZTqzowgkTugUrL8m8nA8SMQi2qf4NTQsJUNqXw0YoZEXsY5OrezJgOPX/6MXuYaYnQnndI3bC0NicxYclwzcWYUOX70EjeTMgsg6/6a0gcS6o9M3dywYCRT4nliKHVcyLVV88XLqtZMEurPDYxkQ6LaDEmhdJOiyOnodljItddpsfKIZ39S6kgwHTEYknE6Yk2JmIzrFdJpsZTPlehrdxYQJtMKUhA2bLmpW7aMNEoUAZQ6FUp2AoxgEwDOg+u6JW03hqSnVPEyJQEIfdAjpJMiYvRUrjQNS9qdDUmjxCWynqQkCKIoCnP7y9t7otgzpNMi6rid4env3wymnWI6GJIulrIeowSCR1wRffvbO1tKU39ZEHvzpNMS6rid4pmdoUIKFuAqG2zYOjPyGiUUPr69/eUd3QURsv7UY7qhSJpbRYwMFVJQbtje7JBsKqWYRyiJ9b3N5S2/mQ/Ws8XuIUVK+HhyBjB6bhz95YbtkQtGOkpW68CfltHeTD5nQ6hXTH+v5YBv1+Gj/83ACBuS5XTEu5RAqh3k8+GcXSAhjXWJabLMspX8WfMnuIKkh+TekDxDSYAD2eZyzi/LCdNJZzJ6SMdVmq4+bjZ/yphGf9SwdWVIHqAEvVqAVjQ9Pe1X5YSpm2CafFylef5Vs9k0JltXhqRS4gZCCYz1wt72Ts4AqCOmLnJu8tVLmi0DRq+MhuTQH/EepeUdvwUgpGkHTF1E0ku6+uK02fyrwZDMK0gep2QNqGMwuR3nJo8BpOPr1w2MLFaQPE7JAZIjJpeUylW6+vz6mWE6UsPTka4ZkUdprDMhMC35O0vPnp25btiSSckBk99FMJ2XStWf68aGbY+GRCilzjXTeXEmnDswVUi0m/4IaZQchrkOKQcZhXMzlobUU7J5mFKPKXdyjtqSuZLBkOSGbW+GRColXcn0qnkNrU7K1wSdnhdhHAEV9ZDcNGxJpeSQck9kRJMBptFozM6yQDxbraZLM/iYm25owxVSuWdD8jYlh2DChaXuyiQGzNf4Kj5Zmk9dpiERS2kdUooc6yHJZ9zQyVINUhcNWzeUOC9Sckg5GElNRjt5q5y6Yam8bnC7HEMyU/rSW5QcgglUTHeauuPJ6uEkkHUpNdmoSzEkcikdQkpquvHqSTeerqmM8Jb/DoYkSSP37o1I7ihlExxJlMb0lLgKw7IyJEpnSJwLQ5JGfkF5PX2vI6f4VxzFcETFEhjkdLHEoFIAuFIlrRgSh7b8dzIk6Rf1EX/phAlSQvIaJXv7Xl/UfImqsCxDQVCxtDL6u5yy3dc95D1SKTkEE6IkY+IYli+gcIKHa9z3R6R7hkec7hBMpFOqsJQcS2yVS9nssO0IqWMwkUkp0qRoJZZYmsWqyg1bFxWSGVInZyKREtyszLAomiiG1YlDO2xdqO0hfx1GSqD2ZtlshcJDnErJXX9Eut/2kPeHktI1qppNg/EMjnEqI9bddERXApBPyb4UmAxMRigKHfTPapQqFfZrV/MRZEqlfD6n+59wm3FL5FBaW11daMj1UTqhQOJB8rmiJOdbJVEoFBKxbC2dzg8nJVHw+RrZoJESS/G8K0ry+FaIYSWy8NN/OP+MdynZG5MILy1ro8TylBtK2LpVSjH0v+G2XvIcJdtY8sP3Sxi/jSlV2QKqKkE9WXZDCZdKCqWCvLHMbe3tOUq2sbQOKQkqJbn2hq/CDSXpVwOlQh591sGWZEqwZiWH0pZooARLJvlGG1eURvWUEviddFzNdgsFjiBKy0ZK0JBklW+5n5sgSoma/EmnyS6ilEgkSIqlTUGjFIxBQ3JPSa0o5VjC/4b9LE6SJEypUmASJMUSupxEjSWVkTtK93WUKrkOoSRtnJ2cbUiIEjwhznltDcVhjBP7oTStUcLODYolG0rS61brwUXrdEQClAoxYEuf+q0be6e01RelUZWS4tz2c7g3reSDiYlkMvlawn3vT5xwfVDaFvqgpPZMComU8qEt0RCEBDG1zm6hf+aTX8TYuy3JP29FieuKkvKRrXW/aSFIE+9ANEVBsdT48hMz6oPSjtgPJdWXGOXxbQtKqXQxIesCYAo1lgZw037PlPDFyb1SwmPctOLcDo2l1wqlJNSu+bJZL1PCodQzJVMHzghJGtnQrfS+DSXVUAIiiNK6crWUQinWpS+N2EOSitFWKHT6b+Vr0kYy+U6F5E1KVkPc+k5d+fleKRmCyWDc0nkoujg2Fg2dK199e5RMXiiQop6k1IZoa9O3ol2wbUnpq66WBu4b91FstKKLE2Nj76LRKAqn+MbNKhdKKpofAKQuKfmX9wTRcAe52CulEekfKEx/Ne+hKEajANLYxINoNPRaio/cmqIo9uXuIEOpm11eW9tzomC8pl0QN+V9uD1QgiZ9b0Qyj23SeXQMaSIAMJ3/VuY4mn3xz9VFBOn9QCB1oqQcTV3f2TcFEZDo2/aPzvROyQBHwSUVAxMyJZBy0dAu++L4cTMU/eCbfx+NfhgMJFtK04BQPj8TxkG00oZIWJlDb2mO9wb2R0naOI2e4EHtX62AknFIoZD8J3xH3oEg8llTmp5e3znII1kHEUy1fXyG3kSJgze5d0sJTPpDFxetM2Tjb1+HQM5NPIkaFRqIbWO1E/LvbM6J6IjqwQG8jcLiDSNE37Lq6kZKdCWVpbum9KYVAlO1i1boDcJUDEUfBKJmeYUSIlRXk0tQbzYxSTjIaaZuoMTXZkozlW4pSSEACeZYCPaQZExtCtWtnsonkjmGXLzViDAD/Eod/PSUuESJqpZi3VJ607pAhg0whWA4xd8et1MaTAmApRDadkcISPwhH0ZgMaVgLJXGlPhSgWOL3VICxfYYHvwBpdaZdDTFLu0aES2GPnxkEI4ChLbcEwISN3Nq/MmUEoWsXAlwlRJL9UJJDiUgQCmUjC5RS0u0CdOACiWsrgjB8X/ZVHICSolCQaaULfK9UPp364GccRchWbCPtGvENFBI3b2DFhzbDIfGp2VKib4ojbw9b10otqQpuquBGlQ12YPaGCFvugRK0tuTJLAmIyTMaXd3fr4+uHKyWwFGVrcz9EVJevP6DRz6AaaWGZFCasC51pVE347NDRbtlLKuKQVaoOI+B5ykt+dJO0zEUBLrdoz6oSQFQhcTEw9aoZIU/9d/jm0oDXZwcy9xbsfhng8rSjddUQLzEji0vQslF/9b5Vhu1yKcooPpunUt+1zrk5JUSspFEnDt5DWaZl/tkmpLznHUbyyN6aqkV9EQHPpNlEgIpc6M/P4SpJTohRIokx4ASO8wD/jbIgKVVFMv6flCCbbZOjLClCo6SmAu544SxBR6YK6SQJHk+/A+CgvwUHTe45CElb0tF4z8/mIwUWEYmVKsyIO5HE+5pBT/7ZXl+J/xZbAGTcFZguiSEaSUZTRKVb6U5dxRim98NVV9YQGJCMPuihGglEqnCphSYSY4k+IpN5TiI19PgR+Z/fm9KZyig1on6U6ucw0J3fiSrsn9JTpVisEtqB0pxeNHU2WKaizdHc/Uo0kjJQIgCeJ+F4wwJbWjS6P93h0pxb+F7yrY4OQ9Nhno1kllYEsOsnPrTt0yMlPCcqYU34DLtVTjoU/diAR8ev7De6Doe89DElb217tj5PeHMaWsW0rYkBo3fObNWiQMa2iJrVtGNpQYB0qqIQ369fYiQdzsgVG3lOLf3oSMGu1vG0uCAKO2NmR3lGIuKMEKyWRIBKl3Rn5/3nUsQUMqWxoSCRKE7Z4ZdUPpqEyuIfXHyDWl+AZDsCH5+mPkkhKukGbJNCSf853Ml0Qpjkd/Mg0JqU9ILijh6cggtvxfmj42JWBIINk4Ug0J6+NSUqZsX5CbbEgfk5JsSFzjSyJHf736hJRzoCQbEs/cJp3RR6QU37gJko2upvFxQ6J1GZRS7ZTiG19D067W/MpxQ6LVP6VgtlJro4SmI2wFbhdfFjs/C6/rMiglmLSJEpyO8PwMPLmyPwSQLiPjUolKykiJkg0JaLub7Yje1SVQCqbMGQcMKQtPsOzUhyGQfB9pjGMr8Dju+t6QMPooVSVfLaFkWxmKZEPql5Jy37lKia4GIaMd68MZhKpfSn7/TEpXL2FDGqJkQ+qfkj8Hb4aXKbEMuh9gc4iSDekSKPn94XQKUqJZZEjLwzH663UplICJp3mKS8ETF1tzw5VsUP8P4qmF5qcurFsAAAAASUVORK5CYII=" jsaction="load:str.tbn" class="rg_ic rg_i" alt="Image result for video" style="width: 293px; height: 172px; margin-left: -9px; margin-right: -22px; margin-top: 2px;" data-atf="1"></a><b><u style="font-family: tahoma, arial, helvetica, sans-serif;"><br></u></b></div><div><b><u style="font-family: tahoma, arial, helvetica, sans-serif;"><br></u></b></div><h1><b>This is a section About Us</b></h1><p>This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text.</p><br><h2>This is another section About Us for your review</h2><p>This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text. This is a paragraph About Us, Filler Text.</p>`

and I am using like this 

                ```
<org.sufficientlysecure.htmltextview.HtmlTextView
                    android:id="@+id/text"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="@dimen/_30sdp"
                    android:text=""
                    app:layout_constraintEnd_toEndOf="@id/guideline3"
                    app:layout_constraintStart_toStartOf="@id/guideline"
                    app:layout_constraintTop_toBottomOf="@+id/connect_line_one" />



text.setHtml(response?.data?.aboutUsDocument?.content!!,HtmlHttpImageGetter(text))
```

**Comment by dschuermann** [comment]
not supported
