### ISSUE TITLE
Cant load base64 images

### ISSUE THREAD

**Issue by generalkolo** [SufficientlySecure/html-textview#179]
Hi, I would like to commend this library as it has come at a time when I needed it the most.
I just want to confirm if I'm doing something wrong or the library doesn't support it yet.
I want to load an image(base64) and it doesn't show up. This is my code - 

@BindingAdapter("bindHtml")
fun HtmlTextView.displayHtmlText(htmlText: String?) {
    val htmltext = "<img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAYAAADhAJiYAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAANFSURBVHgBzVhNUhpBFP5eD2rFqiQTvcDkBJoTiDeQnVQWCcuUMcQTiCdQK6Uu0ZXswg2EG+AJMjmAZlYaY6ZfXg8DDEyPSBzUr2qqoF8P7+P1+23ChDh1jzxW4ZqCswToIsAuQG5XygGBfDD5Iek26dtmOdjyMQHovhtPFw8+kqYPIC5iAoiCjibsly82ju+5fwwR91uRlKrLRw8Pg8+EnXHEMgnV3V13Xs1tM/grcoQc6d6VvtmpBFuBXW7BqbvrKTX7nYFlTAc+6z+rNv8iGxlSs2cYHJF5yY2fqZNSyS/mmHpkiKnDWr1dv9wwzxuG3kG+iE7B6MwkZHwGsWU0U6kcfPJ7svLlZk386QQ5wrhErDNNyIR134GZWkkyfZBuIWcYnSaSU4SI0WdKxFZn5lDl7Uddfd20MiBkrINEnhFTuo2Fw6Fw70YeVTEdeDEHFCKGzNV0wPFuY+FgiSlsMytX8kcVD0+OmYiqAHBMcZj/wDPAjJ7zCoyZtYx07VvWvMTnIH7scuaWJjon6IChXMW8Is55Z6K9Vb9LBYdohS1C1rpSDjZbybXG4uGZKCpGcgq3yhdfjlNyrWWLU7FFaVQXyamLj3iwgpYUZwonB3PYXv/1edWaMgTmDzLTKtKW7aEoUUYecoJJnmP3CFnJ+vs2mbiOa8J+KrnlLmitmrZ1k24KyBkN96AKxbW4i/RDjdL7YKOT3GO+S0oxx5YyhrFQgJxgUoj84t6gpYXnKNQztqf0ypEFuRKCM1u0rC6PVvQuOKWXGb6S4tZGXmDt2ZZf4eXr1CIpmyF+Ktbo4LmAuKUIThPPBKydpoqSGFELTw1Gx3CJ2g8O8+0E/wfi0FGyjAiVA5mVZNrEU0F0RxyQ6BilDlXwRGDm/gDRJ9St7PYaM01oyJgdDKbZoanjWv+tGefCY0GO6kbP15JLlkHxyJMm/0x6SnOrMZK8hm867pYPwR9dMGVCimxptFXJGKV7pPLrlYaUyhA6Ovf1oGwvmI3XfPNuGj5lfOaKX2Q2cfe4jpF7IaLtB1tL/MVE8mhbPDGhYWIyLo1p1NNE2LStJ8lIyoXQgJhc6SFc6w4HYjUiD4NGqzeJtLTmc1Mns44mC/8AQ7R54SABFKgAAAAASUVORK5CYII=\">"
    this.setHtml(htmltext, HtmlHttpImageGetter(this))
}

**Comment by dschuermann** [comment]
does not support it. I am open for pull requests.
