### ISSUE TITLE
Conflicting with OnItemLongClick in listview

### ISSUE THREAD

**Issue by Mathbl** [SufficientlySecure/html-textview#18]
Hello! 

Just ran across a weird issue that took me hours to figure out. I had a listview holding comments (ImageView for the user picture, textview for user name and html-textview for the comment body).

I implemented long click on the listview to be able to select a comment and delete it from action mode.

But when I had a row selected and I scrolled the listview, OnItemLongClick was trigger randomly like I had LongClick a row. 

Turns out when I switch from html-textview to the standard textview, the issue stopped and everything worked as expected. 

If you need me to setup a quick sample project to reproduce the issue, I could do that.

Thanks.

**Comment by dschuermann** [comment]
Any idea how to fix this?

**Comment by Mathbl** [comment]
I actually don't. It might be a conflict with the overridden onTouchEvent.

**Comment by dschuermann** [comment]
Please try version 3.4
