### ISSUE TITLE
HTML.fromHtml adds space at end of text

### ISSUE THREAD

**Issue by benju69** [SufficientlySecure/html-textview#19]
Html.fromHtml adds extra lines after the text. Html class looks at a <p> tag, and append two "\n" chars to the end.

see : http://stackoverflow.com/questions/11882323/html-fromhtml-adds-space-at-end-of-text

**Comment by dschuermann** [comment]
What is you suggestion to do here?

**Comment by Mathbl** [comment]
I think that simply trimming the string before doing setText would do the trick there (like explained in the SO link above).

**Comment by dschuermann** [comment]
This sounds like a good solution: http://stackoverflow.com/a/10187511

**Comment by dr03lf** [comment]
The following is working for me:

```
commentView.setHtmlFromString(comment.bodyHtml, HtmlTextView.RemoteImageGetter())
commentView.text = trimTrailingWhiteSpace(commentView.text)

fun trimTrailingWhiteSpace(source: CharSequence): CharSequence {
        var i  = source.length
        while(--i >= 0 && source.get(i) == '\n'){}
        return source.subSequence(0, i + 1)
}
```

**Comment by dschuermann** [comment]
I am open for pull requests to fix this.

**Comment by dschuermann** [comment]
fixed in https://github.com/SufficientlySecure/html-textview/pull/37
