### ISSUE TITLE
Is there a way to resize images downloaded through RemoteImageGetter ?

### ISSUE THREAD

**Issue by alemedero** [SufficientlySecure/html-textview#23]
I want to force the size of the images downloaded since some of them are downloaded and resized to very small size.

Can i do something with RemoteImageGetter like i would do in ImageGetter by overriding a method like getDrawable ?

**Comment by dschuermann** [comment]
> Can i do something with RemoteImageGetter like i would do in ImageGetter by overriding a method like getDrawable ?

Sure, you could resize the image here, before using it.
Will not consider this for the library.
