### ISSUE TITLE
I am not able to load the remote images.

### ISSUE THREAD

**Issue by Neginal** [SufficientlySecure/html-textview#24]
Below is my path,
"http://4.bp.blogspot.com/-VoMzfclbr4k/Vd3dJpqVMUI/AAAAAAAABGo/gbYcwmbVbjM/s1600/image01.png\"/>", new HtmlTextView.RemoteImageGetter());""

This is not working. Any help is appreciated.

**Comment by Neginal** [comment]
<h2>Hello wold</h2><ul><li>check image</li><li>dogs</li></ul><img src=\"http://4.bp.blogspot.com/-VoMzfclbr4k/Vd3dJpqVMUI/AAAAAAAABGo/gbYcwmbVbjM/s1600/image01.png\"/>", new HtmlTextView.RemoteImageGetter()

**Comment by dschuermann** [comment]
Please open a new issue with a proper example.
