### ISSUE TITLE
Support for databinding

### ISSUE THREAD

**Issue by adarshaj** [SufficientlySecure/html-textview#26]
I would like to use the [databinding](https://developer.android.com/tools/data-binding/guide.html) with html-textview component. Is it worth adding as a feature? Also, if you can provide me pointers of how and where to put in the code I can work on it.

**Comment by andhie** [comment]
You can write your own custom binding

```java
@BindingAdapter({"html"})
public static void displayHtml(HtmlTextView view, @Nullable String html) {
    view.setHtmlFromString(html, new HtmlTextView.RemoteImageGetter());
}
```

the return HTML text method
```java
public String getHtml() {
    return item.getHtml();
}
```

and in XML layout
```xml
<org.sufficientlysecure.htmltextview.HtmlTextView
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:html="@{postModel.html}" />
```

**Comment by dschuermann** [comment]
@andhie can this be integrated into the library? Possibly with an example? I would love to see a pull request for this!

**Comment by andhie** [comment]
Databinding is just helping with the plumbing. You dont need databinding inside the library. what it does is just calling `displayHtml(myHtmlTextView, getHtml());` from your methods

But you can showcase how to use the library with databinding in the example app. if you want, i can submit a pull request for the example.

**Comment by dschuermann** [comment]
@andhie yes an example for databinding inside the README would be awesome.

**Comment by andhie** [comment]
#46
