### ISSUE TITLE
Use without imageGetter.

### ISSUE THREAD

**Issue by naushad-madakiya** [SufficientlySecure/html-textview#30]
Is there is any way to apply html data only without image Getter? there will be no image tag in html data.
In some cases we need only html data to be render on textView not images.

**Comment by dschuermann** [comment]
Why not use LocalImageGetter and simply no img tags?

**Comment by naushad-madakiya** [comment]
That looks like unnecessary argument with no use

**Comment by dschuermann** [comment]
Yes :D

**Comment by dschuermann** [comment]
You can propose an enhancement by making a pull request :)

**Comment by naushad-madakiya** [comment]
Sure, I will try to improve :+1:

**Comment by dschuermann** [comment]
done in 1.7
