### ISSUE TITLE
Trim trailing whitespaces

### ISSUE THREAD

**Issue by renaudfavier** [SufficientlySecure/html-textview#44]
Hi, 

There is an issue with ending \<p> tag with Html.fromHtml that I fixed by using the accepted method of this [stackoverflow topic](http://stackoverflow.com/questions/9589381/remove-extra-line-breaks-after-html-fromhtml
)

The problem is that I can't do it anymore when i use your lib. Would you be kind enough to integrate this bug fix ? 

Thanks.

**Comment by dschuermann** [comment]
This? https://github.com/SufficientlySecure/html-textview/commit/35f1d19077a3078d5d0f476584232e2fbb6bd3fb

**Comment by renaudfavier** [comment]
oh ! I'm sorry it's exactly what I was looking for, thanks it's working like a charm now.

**Comment by dschuermann** [comment]
This is now default in 1.8
