### ISSUE TITLE
can't load remote image

### ISSUE THREAD

**Issue by fengsaofly** [SufficientlySecure/html-textview#48]
I use version 1.8 in gradle
`compile 'org.sufficientlysecure:html-textview:1.8'`

and add the following codes in android

```
        HtmlTextView mTVNewsContent = (HtmlTextView) findViewById(R.id.htNewsContent);
        String newsDetailContent = "<h2>Hello wold</h2><ul><li>cats</li><li>dogs</li></ul><img src=\"http://120.26.39.36/uploads/news/tmp/4495039226559854.jpg\"/>";
        mTVNewsContent.setHtml(newsDetailContent, new HtmlRemoteImageGetter(mTVNewsContent));
```

But, I can't get the image in app.Any helps will be appreciated.

**Comment by dschuermann** [comment]
Is there any related logcat output?

**Comment by saharalmohamady** [comment]
same issue Logcat prints "HtmlTextView: source could not be found:+imageUrl "

**Comment by dschuermann** [comment]
@saharalmohamady this log only comes if you are using the Res or AssetsImageGetter. This issue is about HtmlHttpImageGetter (previously named HtmlRemoteImageGetter)
