### ISSUE TITLE
Custom TagHandler

### ISSUE THREAD

**Issue by DenisMondon** [SufficientlySecure/html-textview#49]
Hi!

If a tag is not supported by your library, is there any way to handle it?

Thanks!

Denis

**Comment by dschuermann** [comment]
There is no way really. Please modify https://github.com/SufficientlySecure/html-textview/blob/master/HtmlTextView/src/main/java/org/sufficientlysecure/htmltextview/HtmlTagHandler.java and make a pull request with your changes.
