### ISSUE TITLE
Extract load raw image from HtmlRemoteImageGetter in a new one (HtmlRawImageGetter)

### ISSUE THREAD

**Issue by danielpassos** [SufficientlySecure/html-textview#50]
Today [HtmlRemoteImageGetter](https://github.com/SufficientlySecure/html-textview/blob/master/HtmlTextView/src/main/java/org/sufficientlysecure/htmltextview/HtmlRemoteImageGetter.java) is loading image from the internet and also from the res/raw, I think it will be a good ideia divide that to be more specific, one for load from the web and another one to load from res/raw

**Comment by dschuermann** [comment]
Can you please point me to the exact line in  HtmlRemoteImageGetter where it loads images from res/raw? I don't see it.

**Comment by danielpassos** [comment]
Nevermind. Wrong issue!
