### ISSUE TITLE
Rename HtmlRemoteImageGetter to HtmlHttpImageGetter

### ISSUE THREAD

**Issue by danielpassos** [SufficientlySecure/html-textview#51]
Change the class name will help it to be auto explained

**Comment by dschuermann** [comment]
Sure HtmlHttpImageGetter is more descriptable, if you like to do this go ahead and create a pull request but please provide backward compatibility.

**Comment by dschuermann** [comment]
Then let's also rename HtmlLocalImageGetter to HtmlResImageGetter. And regarding backward compatibility: Never mind. We can make a 2.0 and remove all the old cruft.

**Comment by danielpassos** [comment]
Going to create another one to HtmlLocalImageGetter to track it in the project
