### ISSUE TITLE
Add @travis-ci

### ISSUE THREAD

**Issue by danielpassos** [SufficientlySecure/html-textview#53]

**Comment by dschuermann** [comment]
Makes only real sense if we have https://github.com/SufficientlySecure/html-textview/issues/54

**Comment by danielpassos** [comment]
@dschuermann I don't agree. Have @travis-ci at less to help community to (automatically) make sure the PR changes don't broke the project in somewhere is a nice reason to have that ;)

I'll work in it asap

**Comment by dschuermann** [comment]
This project is so small, not sure if it justifies the maintanace overhead of Travis. Don't underestimate this, I am working with Travis on OpenKeychain and it just broke again because of Android SDK 24, see https://github.com/open-keychain/open-keychain/pull/1915
