### ISSUE TITLE
i can't handle link when i click image or link in html Textview

### ISSUE THREAD

**Issue by lephuhung** [SufficientlySecure/html-textview#63]
i can't handle link when i click image or link in html Textview. 
Example, when i click a link in the html textview, it open a chrome, firefox,.. but i can get link to open my activity, can you help me, Thank!

**Comment by dschuermann** [comment]
ask on stackoverflow, this is not related to HtmlTextView.

**Comment by dengyuhan** [comment]
I added a custom click event for the a tag, you can try.
[dengyuhan/html-textview](https://github.com/dengyuhan/html-textview/blob/upgrade/NEW-README.md)
