### ISSUE TITLE
Content not shown, only image

### ISSUE THREAD

**Issue by LcTerry** [SufficientlySecure/html-textview#64]
data like this:
    `<div>-2011的相反数是
                         <table name="optionsTable" cellpadding="0" cellspacing="0" width="100%">
                             <tr>
                                <td width="25%">A．2011</td>
                                <td width="25%">B．-2011</td>
                                 <td width="25%">C．<img src="http://192.168.0.126:6001/p/main/download_file/KdjyFileSystem1_11cbaeae-a953-41f6-aae7-8d73e3b104e2.png" style="vertical-align:middle;" /></td>
                                 <td width="25%">D．-<img src="http://192.168.0.126:6001/p/main/download_file/KdjyFileSystem1_11cbaeae-a953-41f6-aae7-8d73e3b104e2.png" style="vertical-align:middle;" /></td>
                            </tr>
                             </table>
                 </div>`
I used like this:
    `text_title.setHtml(R.raw.example, new HtmlHttpImageGetter(text_title));`
Please help me!

**Comment by LomoLin** [comment]
how to solve it?
