### ISSUE TITLE
Unordered list item bullets are not correctly aligned.

### ISSUE THREAD

**Issue by makovkastar** [SufficientlySecure/html-textview#72]
As you can see from the image the bullets are aligned at the bottom of lines instead of being central vertically aligned. Also bullets are cut on their left side.
![device-2016-10-24-120853](https://cloud.githubusercontent.com/assets/1076309/19641919/323ad300-99e3-11e6-966e-21f15ce38e56.png)

**Comment by maxim-yudin** [comment]
I have the same bug when using android:lineSpacingExtra for TextView.

**Comment by dschuermann** [comment]
Please try version 3.6 and report back

**Comment by dschuermann** [comment]
solution and work in progress in https://github.com/SufficientlySecure/html-textview/issues/149
