### ISSUE TITLE
The HtmlTextView supports when HTML content complete filling line after line?

### ISSUE THREAD

**Issue by fuyuguang** [SufficientlySecure/html-textview#75]
The HtmlTextView supports when HTML content complete filling line after line?
For example:
Do not appear as shown in the figure below

<img width="923" alt="the wrong line" src="https://cloud.githubusercontent.com/assets/14189642/20452588/6bff1848-ae48-11e6-9a89-03fedda91ba5.png">

The wrong line 。
Do you have a way to solve this problem?

Chinese language ：
这个 HtmlTextView 是否支持当 html 内容 完整地填充一行后再换行吗？
有好的方法可以解决这个问题吗？

**Comment by dschuermann** [comment]
I don't get the problem.
