### ISSUE TITLE
<span style="color: #ff9900 ... doesn't show the text color

### ISSUE THREAD

**Issue by Hitexroid** [SufficientlySecure/html-textview#81]
In this style

`قابلیت شکل دادن به عکس ( <span style="color: #ff9900;">ستاره ای عکس کردن عکس ؛ چند ضلعی کردن و دایره کردن عکس و &#8230;.</span> )<br />`

**Comment by yogieeka** [comment]
try this http://stackoverflow.com/a/27897258

**Comment by dschuermann** [comment]
This feature is not supported. Please open a pull request to implement it.

**Comment by dengyuhan** [comment]
maybe it can help you.
[dengyuhan/html-textview](https://github.com/dengyuhan/html-textview/blob/upgrade/NEW-README.md)
