### ISSUE TITLE
How can I resize image (HtmlHttpImageGetter) ?

### ISSUE THREAD

**Issue by personaljesusua** [SufficientlySecure/html-textview#85]
I'm trying to resize image so it fits screen size. Setting attributes width and height in `<img/>` tag doesn't work.
I thought of overriding `getDrawable()` method something like that:

       `public Drawable getDrawable(String source) {
        UrlDrawable urlDrawable = new UrlDrawable();

        // get the actual source
        ImageGetterAsyncTask asyncTask = new ImageGetterAsyncTask(urlDrawable, this, container, matchParentWidth);

        asyncTask.execute(source);

        int width = ...;
        int height = ...;
        urlDrawable.setBounds(0, 0, width, height);

        // return reference to URLDrawable which will asynchronously load the image specified in the src tag
        return urlDrawable;
    }`

 but I can't access private class **ImageGetterAsyncTask**. Is there a way to resize image?

**Comment by tpb1908** [comment]
I'm rather late, but HtmlHttpImageGetter has a constructor with the parameter matchParentWidth

```
    public HtmlHttpImageGetter(HtmlTextView textView, String baseUrl, boolean matchParentWidth) {
        this.container = textView;
        this.matchParentWidth = matchParentWidth;
        if (baseUrl != null) {
            this.baseUri = URI.create(baseUrl);
        }
    }
```

If you pass true you can see that Drawable is scaled so that it fits the width of the View

```
        private float getScale(Drawable drawable) {
            final View container = containerReference.get();
            if (!matchParentWidth || container == null) {
                return 1f;
            }
            float maxWidth = container.getWidth();
            float originalDrawableWidth = drawable.getIntrinsicWidth();
            return maxWidth / originalDrawableWidth;
        }
```

See what it looks like below 

![Screenshot](https://github.com/tpb1908/AndroidProjectsClient/blob/master/screenshots/project.png?raw=true)
