### ISSUE TITLE
Give my tag back, please...

### ISSUE THREAD

**Issue by elagin** [SufficientlySecure/html-textview#88]
I need to turn on and off the tag, for example:.
```
private void setStrikeoutText(HtmlTextView view) {
        String original = view.getText().toString();
        if(original != null && original.length() > 0) {
            if(original.contains("<s>")){
                view.setHtml(original.replace("<s>","").replace("</s>",""));
            } else {
                String yy = "<s>" + original + "</s>";
                view.setHtml(yy);
            }
        }
    }
```
The first call to add tags, but again, the query returns only the text, without tags.

**Comment by dschuermann** [comment]
The HTML is converted to Spannables and then displayed. So, the original HTML is lost. You can save the original HTML in a String somewhere but this will not be supported by this library.
