### ISSUE TITLE
image width

### ISSUE THREAD

**Issue by distancelin** [SufficientlySecure/html-textview#92]
I've got html string,but when I tried to show the Image by html-textview,I got a pretty small image on screen.So how can I enlarge images to my screen width?

**Comment by slnepal** [comment]
I also ran into same problem. The last argument is matchParentWidth which is boolean in HtmlHttpImageGetter constructor. I don't know your case this is piece of code is working for me.

HtmlTextView htmlTextView = (HtmlTextView) findViewById(R.id.html_text)
htmlTextView.setHtml( string_data, new HtmlHttpImageGetter(htmlTextView, base_url , true));

**Comment by distancelin** [comment]
Thanks for your answer,which actually works for me.
