### ISSUE TITLE
Setting the size of DrawTableLinkSpan text seems to be broken

### ISSUE THREAD

**Issue by vishnumad** [SufficientlySecure/html-textview#98]
Looks like line 55 here is resetting the text size of the span: [DrawTableLinkSpan.java](https://github.com/SufficientlySecure/html-textview/blob/master/HtmlTextView/src/main/java/org/sufficientlysecure/htmltextview/DrawTableLinkSpan.java#L55)

**Comment by dschuermann** [comment]
Please open a pull request to fix stuff.
